project:
  type: book
  output-dir: docs

book:
  title: "CASA0023"
  author: "Jan Magnuszewski"
  date: "1/16/2024"
  chapters:
    - index.qmd
    - wk1.qmd
    - wk2.qmd
    - wk3.qmd
    - wk4.qmd
    - wk6.qmd
    - wk7.qmd
    - wk8.qmd
    - wk9.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

