project:
  type: book
  output-dir: docs

book:
  title: "CASA0023"
  author: "Jan Magnuszewski"
  date: "1/16/2024"
  navbar:
    collapse: true
    collapse-below: lg
    background: light
    search: true
    tools:
      - icon: github
      - icon: twitter
        href: https://twitter.com/jankomag
      - icon: linkedin
        href: https://www.linkedin.com/in/jan-magnuszewski-77718214a/
  sidebar:
    title: "CASA0023"
    style: floating
    reader-mode: true
  repo-url: https://github.com/jankomag/CASA0023
  chapters:
    - index.qmd
    - wk1.qmd
    - wk2.qmd
    - wk3.qmd
    - wk4.qmd
    - wk6.qmd
    - wk7.qmd
    - wk8.qmd
    - wk9.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
        light: [sandstone, flatly]
        dark: [sandstone, darkly]
  pdf:
    documentclass: scrreprt

editor: visual

