# Policy applications {#sec-week4}

This page contains a discussion of a chosen real-world issue facing a city, and how it could be addressed with remote sensing. 

## Summary

I recently read an article about an issue that the city of Melbourne is facing, which could potentially benefit from analysis of remote sensing data [@guardian2024]. The issue described in the article is about the land on the city's fringes being converted from farmland into low-rise suburban developments. The land surrounding the city has some of the richest and most productive soils in the state of Victoria, which is important for both food security and the local, rural economy. The new developments encroaching onto this land are also associated with increased fire risk, which is a very important issue in this region of Australia [@stanley2020].

There is a lack of policies in Melbourne that would address this issue and constrain where developments are allowed to happen, given the potential of the land for agriculture. Of course, completely halting new developments in Melbourne is a really bad idea, due to the city's very unaffordable housing market and projected population growth. Curbing the supply of new housing would put even more pressure on the already strained property market. That is why it is important the city allows for more urban intensification, and designates areas where the city should be growing through densification, not just through sprawl. This is an increasingly discussed topic in Melbourne with a growing community of missing-middle advocates [@yimby_melbourne_2023]. Therefore, the need for more housing in Melbourne is a twofold problem - firstly protecting the existing farmlands on city's fringes, and secondly building more affordable housing in the city in the form of apartments and townhouses.

## Applications

In order to address this issue from both sides, policies would need to be developed that for one identify the most important areas of farmlands that would need to be protected and secondly identify inner-city areas where urban densification is most suitable. For example around the currently under-construction Melbourne Suburban Rail Loop stations where densification is being prioritised. This is where remote sensing data could help.

Using satellite imagery we could identify the most important farmlands, which should be prioritised over developments. The identification of soil quality and the valuation of natural environments are applications where remote sensing can be used [@hazeu2014high]. Furthermore for finding areas of densification, remote sensing might not be an obvious choice, but could help e.g. in assessing the greenness of urban areas or soil permeability - all important aspects in order for the city to densify sustainably.

## Reflections

The approach outlined above of using remotely sensed data for this issue, may not be the best choice for all aspects of the problem. Firstly, it would require using very high-resolution imagery to be able to identify features like buildings or individual trees. Secondly, for analysis of urban areas where densification potential is highest, a natural choice would be to rely on vector data, e.g. population data aggregated to spatial units, or transport and infrastructure data.

The Melbourne Plan 2017-2050 mentions in its implementation the importance of using spatial data for planning new developments and open spaces [@planmelbourne]. The plan even mentions in one section how the city will "protect the right to farm in key locations within green wedges and peri-urban areas". However, the specific methodology or mention of remote sensing methods is lacking.